{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-state-metrics.serviceAccountName" . }}
  namespace: {{ include "kube-state-metrics.namespace" . }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end -}}

{{- if .Values.serviceAccount.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  {{ if has "configmaps" $.Values.collectors }}
  - apiGroups: [""]
    resources:
    - configmaps
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "secrets" $.Values.collectors }}
  - apiGroups: [""]
    resources:
    - secrets
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "nodes" $.Values.collectors }}
  - apiGroups: [""]
    resources:
    - nodes
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "pods" $.Values.collectors }}
  - apiGroups: [""]
    resources:
    - pods
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "services" $.Values.collectors }}
  - apiGroups: [""]
    resources:
    - services
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "resourcequotas" $.Values.collectors }}
  - apiGroups: [""]
    resources:
    - resourcequotas
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "replicationcontrollers" $.Values.collectors }}
  - apiGroups: [""]
    resources:
    - replicationcontrollers
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "limitranges" $.Values.collectors }}
  - apiGroups: [""]
    resources:
    - limitranges
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "persistentvolumeclaims" $.Values.collectors }}
  - apiGroups: [""]
    resources:
    - persistentvolumeclaims
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "persistentvolumes" $.Values.collectors }}
  - apiGroups: [""]
    resources:
    - persistentvolumes
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "namespaces" $.Values.collectors }}
  - apiGroups: [""]
    resources:
    - namespaces
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "endpoints" $.Values.collectors }}
  - apiGroups: [""]
    resources:
    - endpoints
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "statefulsets" $.Values.collectors }}
  - apiGroups: ["apps"]
    resources:
    - statefulsets
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "daemonsets" $.Values.collectors }}
  - apiGroups: ["apps"]
    resources:
    - daemonsets
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "deployments" $.Values.collectors }}
  - apiGroups: ["apps"]
    resources:
    - deployments
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "replicasets" $.Values.collectors }}
  - apiGroups: ["apps"]
    resources:
    - replicasets
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "cronjobs" $.Values.collectors }}
  - apiGroups: ["batch"]
    resources:
    - cronjobs
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "jobs" $.Values.collectors }}
  - apiGroups: ["batch"]
    resources:
    - jobs
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "horizontalpodautoscalers" $.Values.collectors }}
  - apiGroups: ["autoscaling"]
    resources:
    - horizontalpodautoscalers
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "poddisruptionbudgets" $.Values.collectors }}
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "certificatesigningrequests" $.Values.collectors }}
  - apiGroups: ["certificates.k8s.io"]
    resources:
    - certificatesigningrequests
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "storageclasses" $.Values.collectors }}
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "volumeattachments" $.Values.collectors }}
  - apiGroups: ["storage.k8s.io"]
    resources:
      - volumeattachments
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "mutatingwebhookconfigurations" $.Values.collectors }}
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "validatingwebhookconfigurations" $.Values.collectors }}
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - validatingwebhookconfigurations
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "networkpolicies" $.Values.collectors }}
  - apiGroups: ["networking.k8s.io"]
    resources:
    - networkpolicies
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "ingresses" $.Values.collectors }}
  - apiGroups: ["networking.k8s.io"]
    resources:
    - ingresses
    verbs: ["list", "watch"]
  {{ end -}}
  {{ if has "roles" $.Values.collectors }}
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
    - roles
    verbs: ["list", "watch"]
  {{ end -}}
  {{-  if $.Values.kubeRBACProxy.enabled  }}
  - apiGroups: ["authentication.k8s.io"]
    resources:
      - tokenreviews
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - subjectaccessreviews
    verbs: ["create"]
  {{- end }}
  {{- if .Values.serviceAccount.rbac.pspEnabled }}
  - apiGroups: ["policy"]
    resources:
      - podsecuritypolicies
    verbs: ["use"]
    resourceNames:
      - {{ include "kube-state-metrics.fullname" . }}
  {{- end }}
  {{- if .Values.sharding.enabled }}
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-state-metrics.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-state-metrics.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}

{{- if and .Values.serviceAccount.rbac.create .Values.sharding.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}-sharding
  namespace: {{ include "kube-state-metrics.namespace" . }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}-sharding
  namespace: {{ include "kube-state-metrics.namespace" . }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kube-state-metrics.fullname" . }}-sharding
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-state-metrics.serviceAccountName" . }}
    namespace: {{ include "kube-state-metrics.namespace" . }}
{{- end }}